spring.application.name=ecommerce


#===============================
# Configuring Database source
#===============================

spring.datasource.url=jdbc:postgresql://localhost:5432/spring_ecommerce
spring.datasource.password=theo123
spring.datasource.username=postgres

#=======================
# JPA Hibernate configs
#=======================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgresSQLDialect


# ================================
# HikariCP Connection Pool Config
#=================================
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.maximum-pool-size=20
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.pool-name=HikariPool-1

#====================================
# Spring Custom Security configuring
#====================================
spring.security.user.name=user
spring.security.user.password=theo123
spring.security.user.roles=ADMIN

#===========
#urls

app.frontend.url=http://localhost:3000

#=============
#Mailer configuring
#=============

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dufitimanatheoneste05@gmail.com
spring.mail.password=bxas gclb owkx espa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


#google auth configuration
spring.security.oauth2.client.registration.google.client-id=424738073773-4jbpd6ttg25clb99c6ejq626jhojdkrs.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/api/auth/oauth2/callback/{registrationId}
spring.security.oauth2.client.registration.google.client-name=Google
spring.security.oauth2.client.provider.google.authorization-uri=https://accounts.google.com/o/oauth2/v2/auth
spring.security.oauth2.client.provider.google.token-uri=https://oauth2.googleapis.com/token
spring.security.oauth2.client.provider.google.user-info-uri=https://www.googleapis.com/oauth2/v3/userinfo
